name: Deploy the MkDocs Documentation

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install MkDocs and dependencies
      - name: Install MkDocs and Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pip-tools
          make dependencies
          make test-dependencies
          make doc-dependencies

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
