name: Run Python Unit Tests

on: 
  push:
    branches:
      - main  # Trigger tests on push to main branch
  pull_request:
    branches:
      - main  # Trigger tests on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Run the unit tests without installing any dependencies
      - name: Run Unit Tests
        run: |
          python -m pip install pytest pytest-cov
          python -m pytest --cov=. --cov-report=html tests/test_helpers.py
          

      - name: Upload Coverage Report
        run: aws s3 sync htmlcov s3://luit-aug-2024-silver-cicd-beta/htmlcov/ --acl public-read
